C:\python27\python.exe WorkQueues_NewTask.py Task1...
C:\python27\python.exe WorkQueues_NewTask.py Task2......
C:\python27\python.exe WorkQueues_NewTask.py Task3....
C:\python27\python.exe WorkQueues_NewTask.py Task4.......
C:\python27\python.exe WorkQueues_NewTask.py Task5...
C:\python27\python.exe WorkQueues_NewTask.py Task6........